[package]
name = "greentic-interfaces"
edition.workspace = true
version.workspace = true
license.workspace = true
authors = ["Greentic <engineering@greentic.dev>"]
description = "Stub Greentic interface bindings"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
