[package]
name = "greentic-types"
edition.workspace = true
version.workspace = true
license.workspace = true
authors = ["Greentic <engineering@greentic.dev>"]
description = "Stub Greentic types for PackSpec"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
