name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable

      - name: crate versions
        run: cargo metadata --format-version 1

      - name: Publish pack_component
        run: cargo publish -p pack_component --locked

      - name: Wait for crates.io index
        run: sleep 20

      - name: Publish packc
        run: cargo publish -p packc --locked
