name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable

      - name: crate versions
        run: cargo metadata --format-version 1

      - name: Publish pack_component
        shell: bash
        run: |
          set -euo pipefail
          if output=$(cargo publish -p pack_component --locked 2>&1); then
            echo "$output"
          else
            status=$?
            echo "$output"
            if grep -qi "already uploaded" <<<"$output" || grep -qi "already exist" <<<"$output"; then
              echo "pack_component version already on crates.io; continuing."
            else
              exit $status
            fi
          fi

      - name: Wait for crates.io index
        run: sleep 20

      - name: Publish packc
        shell: bash
        run: |
          set -euo pipefail
          if output=$(cargo publish -p packc --locked 2>&1); then
            echo "$output"
          else
            status=$?
            echo "$output"
            if grep -qi "already uploaded" <<<"$output" || grep -qi "already exist" <<<"$output"; then
              echo "packc version already on crates.io; continuing."
            else
              exit $status
            fi
          fi
